import React from 'react'
import Header from "@/components/Header"
import Footer from "@/components/Footer"
import '@/styles/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
